sudo: false
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/repositories/"
language: groovy
jdk:
- oraclejdk8
env:
  - TRAVIS_NODE_VERSION="5.6.0"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 5.6.0
  - npm install
script:
  - npm run package
  - gradle clean jar
