sudo: false
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/repositories/"
language: groovy
jdk:
- oraclejdk8
install: true
script: gradle clean install
env:
  global:
  - secure: eR/cYREdZ75hfUjbtdCWi3wL/BuL3Sp1bCPShPYTZhan/KCbpIaG3FR4/IhEN34jNsBgMpGZwW7rOx5eWhfCF+7VVNnDSvxw0imIKfDs+1WfNEE9gHtmgF/ogvPfKyEzF4kSL8Wd0pDA0l9/Os/D8NpTiOPqNzd6m05cd7onE0lUUbqsfURjEt47A1NZElfkKBS94T90U1DWsJH+0DZnGcRnLp2kKX7VdiU2Qz9VHJIzJvvpgRabE54KgJua4GUn75GdVpO8Nhmx0Bsif/QTbqefbdPRjaUFzuIEF1/tLEv5FsKAYLTxNq0x0K9d/DkXEGPFCdacfFcLwDnK8BftKWoNxbeMSo0+NVyMBKErqiGPn0e9wf4QmncTF1ZqxiuGftf3a670pM07Uh4d3bf2IU6FZPGF82T0pgrGL69l+IqKPCSLxhdtzGM1Gb68UUXjNnB0uc9vLoDWXZdckoEy/rmLJhs6Pq2G1U8ijT61npTpjPMcM3fy4YXfJQfyDsYkG0GciDGnibiV3sbrXPWOQD+Go7RGnp0kp60GQXVkexT4GcHwXys2RhFMp5ZuQ7QptlWcvzEEyhxO9/OZgjN+H3rJvLbpAW/CHgX1gpZHZt2VBl748zsdtOI9B0mLSDk5ib6wtL+ZKK9uNHx0GoMdEiqy+pXLdxVovYPHCt8kNBM=
  - secure: lDJSPqSwfv0k0Q6rvck6Aj1b+bwkK030aU/U+GB66/FlRjqHJNy1VRzw1bF/pO1bNDTGWrmVsWy6AKlQEaqo8B6JKvW8iVYoj1YaDlf9+zgnLJ+M1JNJXUbWWZYylYBhWdtiS8R6mHuY7wP7wHypPANM/a18xwWDwq5d17FwFuDh6eIA63+9yi+OcsGNMQGQLGtybOgiHJHI/K8V2BfmO0ZSIXjHDI/ATgH+LexFejH00uFlwPFCyBnA1QLDfMxJFpZGVavAZEMgOT1Cm1BU2VWIHwsQdo5KMe8vF3Fu6dopPRxyDgl6h5hVFVbXwx6lQUkRs6bAy5ox9e84l5QsygEmHpGgaU1REe0CbpooD97nNoUDByxHWFrYX/u30R49kTQgFFjha9mVt2nVlGf46UOjLCanspDuulBfDCtZ5Sd5tfKdm9WF51tTA4hEV1QWeH1NN6RGH3+5qXJCvygndeajpqMXahuBt7aCvSry1s5DvsK7ODg2P7J2lfU+qsCIEQIT0Uhm8zUsHr6I+Hqz+Vk/6qQ9O0EzqMBQskVb0LcVOaBeDe7wPZi7hKrqZAMSDqbmUbktd1spHo99xroJkCnrnuK8xLOF7TQyFLP5nIfkYtdx9knNzDHraBaFBT2MdcSNxe6luPHb5zWp0Se8ac3GCSsc6+20dIrhAEWpDdA=
deploy:
  provider: script
  script: gradle bintrayUpload
  on:
    tags: true